apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-backend
  labels:
    app: {{ include "mern-chart.name" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mern-chart.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "mern-chart.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
{{- range .Values.backend.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
{{- end }}
